### ISSUE TITLE
Cannot pip-install 0.5.1: missing CHANGELOG.rst

### ISSUE THREAD

**Issue by mkorvas** [kraiz/hamster-bridge#19]
Hi, thanks for this useful plugin, really looking forward to using it!

I tried to install it using straightforward `pip install hamster-bridge` issued as a root user (I trust you;) ) but it failed like follows:
```
$ /usr/bin/pip install hamster-bridge
Downloading/unpacking hamster-bridge
  Downloading hamster-bridge-0.5.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/hamster-bridge/setup.py) egg_info for package hamster-bridge
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/hamster-bridge/setup.py", line 18, in <module>
        long_description=open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read(),
    IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/hamster-bridge/setup.py", line 18, in <module>

    long_description=open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read(),

IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/hamster-bridge
Storing debug log for failure in /home/matej/.pip/pip.log
```

In contrast, installing version 0.5.0 worked fine:
```
$ pip install hamster-bridge==0.5.0
Downloading/unpacking hamster-bridge==0.5.0
  Downloading hamster_bridge-0.5.0-py2-none-any.whl
Downloading/unpacking jira>=0.40 (from hamster-bridge==0.5.0)
  Downloading jira-1.0.3-py2.py3-none-any.whl (46kB): 46kB downloaded
Downloading/unpacking six>=1.9.0 (from jira>=0.40->hamster-bridge==0.5.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking requests>=2.6.0 (from jira>=0.40->hamster-bridge==0.5.0)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Downloading/unpacking tlslite>=0.4.4 (from jira>=0.40->hamster-bridge==0.5.0)
  Downloading tlslite-0.4.9.tar.gz (105kB): 105kB downloaded
  Running setup.py (path:/tmp/pip_build_root/tlslite/setup.py) egg_info for package tlslite
    
    warning: no files found matching '*' under directory 'docs'
Downloading/unpacking requests-oauthlib>=0.3.3 (from jira>=0.40->hamster-bridge==0.5.0)
  Downloading requests_oauthlib-0.6.0-py2.py3-none-any.whl
Downloading/unpacking requests-toolbelt (from jira>=0.40->hamster-bridge==0.5.0)
  Downloading requests_toolbelt-0.6.0-py2.py3-none-any.whl (48kB): 48kB downloaded
Downloading/unpacking oauthlib>=0.6.2 (from requests-oauthlib>=0.3.3->jira>=0.40->hamster-bridge==0.5.0)
  Downloading oauthlib-1.0.3.tar.gz (109kB): 109kB downloaded
  Running setup.py (path:/tmp/pip_build_root/oauthlib/setup.py) egg_info for package oauthlib
    
Installing collected packages: hamster-bridge, jira, six, requests, tlslite, requests-oauthlib, requests-toolbelt, oauthlib
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for tlslite
    changing mode of build/scripts-2.7/tls.py from 644 to 755
    changing mode of build/scripts-2.7/tlsdb.py from 644 to 755
    
    warning: no files found matching '*' under directory 'docs'
    changing mode of /usr/local/bin/tlsdb.py to 755
    changing mode of /usr/local/bin/tls.py to 755
  Found existing installation: oauthlib 0.6.1
    Not uninstalling oauthlib at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for oauthlib
    
Successfully installed hamster-bridge jira six requests tlslite requests-oauthlib requests-toolbelt oauthlib
Cleaning up...
```

**Comment by kraiz** [comment]
Hey @mkorvas,

that's a quite simple packaging error. I wonder why this didn't happen to me...

Anyway...it's fixed and 0.5.2 is on pypi.

```
pip install -U hamster-bridge
```
