### ISSUE TITLE
Jira 7.3.0+ not working

### ISSUE THREAD

**Issue by Fank** [kraiz/hamster-bridge#26]
It looks like the authentication do not work anymore.
I'm not familiar with Python so debugging could take a while.

Info:
- ssl validation is disabled.
Log:
```
2017-02-14 15:39:40,882    INFO: Starting hamster bridge
2017-02-14 15:39:40,885 WARNING: Disabling SSL/TLS certificate verification
2017-02-14 15:39:40,885    INFO: Connecting as "ASDASDASD" to "https://jira.mcl.de"
2017-02-14 15:39:40,890    INFO: Starting new HTTPS connection (1): jira.mcl.de
/home/mfkinder/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/home/mfkinder/.local/bin/hamster-bridge", line 11, in <module>
    sys.exit(main())
  File "/home/mfkinder/.local/lib/python2.7/site-packages/hamster_bridge/__init__.py", line 53, in main
    bridge.run(args.check_interval)
  File "/home/mfkinder/.local/lib/python2.7/site-packages/hamster_bridge/bridge.py", line 98, in run
    listener.prepare()
  File "/home/mfkinder/.local/lib/python2.7/site-packages/hamster_bridge/listeners/jira.py", line 83, in prepare
    basic_auth=(username, password)
  File "/home/mfkinder/.local/lib/python2.7/site-packages/jira/client.py", line 261, in __init__
    si = self.server_info()
  File "/home/mfkinder/.local/lib/python2.7/site-packages/jira/client.py", line 1619, in server_info
    return self._get_json('serverInfo')
  File "/home/mfkinder/.local/lib/python2.7/site-packages/jira/client.py", line 2035, in _get_json
    r = self._session.get(url, params=params)
  File "/home/mfkinder/.local/lib/python2.7/site-packages/jira/resilientsession.py", line 130, in get
    return self.__verb('GET', url, **kwargs)
  File "/home/mfkinder/.local/lib/python2.7/site-packages/jira/resilientsession.py", line 126, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/mfkinder/.local/lib/python2.7/site-packages/jira/resilientsession.py", line 45, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 401
	text: 









<html>

<head>
    <title>Unauthorized (401)</title>
..... and more HTML
```

**Comment by Fank** [comment]
nvm works fine :+1:
